import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft, Eye, EyeOff, Database, Mail, Trash2 } from "lucide-react";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";

const TITLE = "Privacy";
const DESC =
  "What viberank collects, what is public, what is not, and how to have any of it deleted.";

export const metadata: Metadata = {
  title: TITLE,
  description: DESC,
  alternates: { canonical: "https://www.viberank.app/privacy" },
  openGraph: {
    title: TITLE,
    description: DESC,
    url: "https://www.viberank.app/privacy",
    type: "article",
  },
  robots: { index: true, follow: true },
};

/** Last substantive change to this page. Update when the content changes. */
const UPDATED = "28 August 2026";

type Row = { what: string; why: string };

const PUBLIC_DATA: Row[] = [
  {
    what: "GitHub username, display name and avatar",
    why: "Identifies your row on the leaderboard and your profile page.",
  },
  {
    what: "Usage totals from ccusage — token counts, API-equivalent cost, dates active, models and tools used",
    why: "This is the leaderboard. It is the data you chose to submit.",
  },
  {
    what: "Per-day breakdowns of the above",
    why: "Powers profile charts, monthly reports and the public dataset.",
  },
  {
    what: "League names and membership, if you join one",
    why: "A league board has to name its members.",
  },
  {
    what: "Open-to-work flag and the contact address you enter there, if you opt in",
    why: "The whole point of /hire is that someone can reach you. Only shown if you switch it on.",
  },
];

const PRIVATE_DATA: Row[] = [
  {
    what: "Your email address from GitHub sign-in",
    why: "Stored so we can reach you about your own data and, in future, about the service. Never displayed, never listed, never sold. Nothing is sent to it today.",
  },
  {
    what: "A machine ID generated by the CLI",
    why: "A random UUID created on your machine so a laptop and a desktop add up instead of overwriting each other. Not derived from your hardware, and not tied to anything outside viberank.",
  },
  {
    what: "API tokens",
    why: "Stored only as a hash, plus a short display fragment. The token itself is shown once and never again.",
  },
  {
    what: "The raw ccusage report you submit, and file/byte counts of your session-log folder",
    why: "Kept to re-check totals and catch double-counting. Counts only — never the contents of your code, prompts or transcripts.",
  },
];

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-background">
      <NavBar />

      <div className="max-w-3xl mx-auto px-6 py-12">
        <Link
          href="/"
          className="inline-flex items-center gap-1.5 micro-label hover:text-foreground transition-colors mb-6"
        >
          <ArrowLeft className="w-3.5 h-3.5" />
          Leaderboard
        </Link>

        <p className="micro-label mb-3">Privacy</p>
        <h1 className="font-mono text-3xl font-bold tracking-tight text-foreground mb-3">
          What viberank knows about you
        </h1>
        <p className="text-muted leading-relaxed mb-8">
          viberank is a leaderboard, so most of what it holds is public on purpose — that is what you
          came here to do. This page is about the rest: what is collected that is{" "}
          <em>not</em> on display, why it exists, and how to get rid of it. Last updated {UPDATED}.
        </p>

        <div className="rounded-lg border border-accent/40 bg-surface-1 p-5 mb-12">
          <p className="text-foreground m-0 leading-relaxed">
            The short version: your usage figures and GitHub handle are public. Your email address and
            submission metadata are not, and are readable only by the server. viberank has never sent a
            marketing email, has no mailing list, and sells nothing to anyone.
          </p>
        </div>

        <section className="mb-12">
          <h2 className="font-mono text-lg font-bold tracking-tight mb-4 flex items-center gap-2">
            <Eye className="w-4 h-4 text-accent" />
            Public — visible to anyone
          </h2>
          <div className="rounded-lg border border-border overflow-hidden">
            {PUBLIC_DATA.map((r, i) => (
              <div
                key={r.what}
                className={`bg-surface-1 p-4 ${i > 0 ? "border-t border-border" : ""}`}
              >
                <p className="text-foreground text-sm font-medium m-0 mb-1">{r.what}</p>
                <p className="text-muted text-sm m-0 leading-relaxed">{r.why}</p>
              </div>
            ))}
          </div>
          <p className="text-muted text-sm leading-relaxed mt-4">
            Public means public: the leaderboard, profile pages and the{" "}
            <Link href="/data" className="text-accent hover:underline">
              open dataset
            </Link>{" "}
            are all readable without an account, and search engines index them.
          </p>
        </section>

        <section className="mb-12">
          <h2 className="font-mono text-lg font-bold tracking-tight mb-4 flex items-center gap-2">
            <EyeOff className="w-4 h-4 text-accent" />
            Not public — server only
          </h2>
          <div className="rounded-lg border border-border overflow-hidden">
            {PRIVATE_DATA.map((r, i) => (
              <div
                key={r.what}
                className={`bg-surface-1 p-4 ${i > 0 ? "border-t border-border" : ""}`}
              >
                <p className="text-foreground text-sm font-medium m-0 mb-1">{r.what}</p>
                <p className="text-muted text-sm m-0 leading-relaxed">{r.why}</p>
              </div>
            ))}
          </div>
        </section>

        <section className="mb-12">
          <h2 className="font-mono text-lg font-bold tracking-tight mb-4 flex items-center gap-2">
            <Mail className="w-4 h-4 text-accent" />
            About your email address
          </h2>
          <div className="space-y-4 text-muted leading-relaxed text-sm">
            <p>
              Signing in with GitHub asks for the <code className="font-mono text-accent">user:email</code>{" "}
              scope, which GitHub shows you on its consent screen. As of {UPDATED} that address is stored,
              in a table the public site cannot read. Before that date it was requested but discarded, so
              if you signed in earlier and never returned, viberank does not have it.
            </p>
            <p>
              It is used to contact you about your own data and about the service — for example, that a
              feature you rely on broke. It is not used for marketing, is not shared with sponsors, and is
              not sold. If that ever changes, this page changes first, and anything resembling a newsletter
              will be opt-in with an unsubscribe link.
            </p>
            <p>
              The address shown on{" "}
              <Link href="/hire" className="text-accent hover:underline">
                /hire
              </Link>{" "}
              is separate. You type that one in yourself, it only appears if you turn the open-to-work
              flag on, and turning the flag off removes it.
            </p>
          </div>
        </section>

        <section className="mb-12">
          <h2 className="font-mono text-lg font-bold tracking-tight mb-4 flex items-center gap-2">
            <Database className="w-4 h-4 text-accent" />
            Third parties
          </h2>
          <div className="space-y-4 text-muted leading-relaxed text-sm">
            <p>
              <span className="text-foreground font-medium">Vercel</span> hosts the site and provides
              analytics. Vercel Analytics is cookieless and aggregate — page views and referrers, not
              individual people.
            </p>
            <p>
              <span className="text-foreground font-medium">Supabase</span> hosts the database.
            </p>
            <p>
              <span className="text-foreground font-medium">GitHub</span> handles sign-in. viberank never
              sees your GitHub password.
            </p>
            <p>
              There are no advertising trackers and no third-party analytics beyond the above. Sponsor
              placements, where they appear, are static — they do not track you.
            </p>
          </div>
        </section>

        <section className="mb-12">
          <h2 className="font-mono text-lg font-bold tracking-tight mb-4 flex items-center gap-2">
            <Trash2 className="w-4 h-4 text-accent" />
            Deleting your data
          </h2>
          <div className="space-y-4 text-muted leading-relaxed text-sm">
            <p>
              You can delete individual submissions yourself at{" "}
              <Link href="/settings/submissions" className="text-accent hover:underline">
                /settings/submissions
              </Link>
              .
            </p>
            <p>
              To remove your profile and everything attached to it — submissions, daily breakdowns, stored
              email, tokens and submission metadata —{" "}
              <a
                href="https://github.com/sculptdotfun/viberank/issues/new"
                target="_blank"
                rel="noopener noreferrer"
                className="text-accent hover:underline"
              >
                open an issue
              </a>{" "}
              from the GitHub account in question, or email the address in the repository. Asking from the
              account is what proves it is yours. Deletion is permanent and is not recoverable.
            </p>
            <p>
              Figures already included in published aggregates — a monthly report, the blog, the open
              dataset — cannot be retroactively unpicked from those totals, because they are sums, not
              rows. Nothing in them identifies you.
            </p>
          </div>
        </section>

        <section className="mb-12">
          <h2 className="font-mono text-lg font-bold tracking-tight mb-4">Changes</h2>
          <p className="text-muted leading-relaxed text-sm">
            viberank is open source. Every change to what is collected is a commit in{" "}
            <a
              href="https://github.com/sculptdotfun/viberank"
              target="_blank"
              rel="noopener noreferrer"
              className="text-accent hover:underline"
            >
              the public repository
            </a>
            , and the schema is in <code className="font-mono text-accent">supabase/migrations</code> if
            you would rather read it than take our word for it. Material changes to this page will be
            noted in the changelog.
          </p>
        </section>
      </div>

      <Footer />
    </div>
  );
}
